union_jack = """
|RRRWWWWBBBBBBBBBBWWRRWWBBBBBBBBBBWWWWRRR|
|WWRRWWWWWBBBBBBBBWWRRWWBBBBBBBBWWWWWRRWW|
|BWWWRRWWWWWBBBBBBWWRRWWBBBBBBWWWWWRRWWWB|
|BBBWWWRRWWWWWBBBBWWRRWWBBBBWWWWWRRWWWBBB|
|BBBBBWWWRRWWWWBBBWWRRWWBBBWWWWRRWWWBBBBB|
|WWWWWWWWWWWWWWWWWWWRRWWWWWWWWWWWWWWWWWWW|
|RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR|
|WWWWWWWWWWWWWWWWWWWRRWWWWWWWWWWWWWWWWWWW|
|BBBBBWWWRRWWWWBBBWWRRWWBBBWWWWRRWWWBBBBB|
|BBBWWWRRWWWWWBBBBWWRRWWBBBBWWWWWRRWWWBBB|
|BWWWRRWWWWWBBBBBBWWRRWWBBBBBBWWWWWRRWWWB|
|WWRRWWWWWBBBBBBBBWWRRWWBBBBBBBBWWWWWRRWW|
|RRRWWWWBBBBBBBBBBWWRRWWBBBBBBBBBBWWWWRRR|
"""

old_glory = """
|*B*B*B*B*B*B*B*B*B*BRRRRRRRRRRRRRRRRRRRRRRRRR|
|B*B*B*B*B*B*B*B*B*BBWWWWWWWWWWWWWWWWWWWWWWWWW|
|*B*B*B*B*B*B*B*B*B*BRRRRRRRRRRRRRRRRRRRRRRRRR|
|B*B*B*B*B*B*B*B*B*BBWWWWWWWWWWWWWWWWWWWWWWWWW|
|*B*B*B*B*B*B*B*B*B*BRRRRRRRRRRRRRRRRRRRRRRRRR|
|B*B*B*B*B*B*B*B*B*BBWWWWWWWWWWWWWWWWWWWWWWWWW|
|*B*B*B*B*B*B*B*B*B*BRRRRRRRRRRRRRRRRRRRRRRRRR|
|WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|
|RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR|
|WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|
|RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR|
|WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW|
|RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR|
"""

the_maple_leaf = """
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWRWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWRWWWWWRRRRRWWWWWRWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWRRRWWRRRRRRRWWRRRWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWRWWWWRRRRRRRRRRRRRRRRRWWWWRWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWRRRRWWWRRRRRRRRRRRRRRRWWWRRRRWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWRRRRRRRRRRRRRWRRRRRRRRRRRRRRRWRRRRRRRRRRRRRWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWRRRRRRRRRRRRRRRRRRRRRRRRRRRRRWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWRRRRRRRRRRRRRRRRRRRRRRRWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWRRRRRRRRRRRRRRRRRRRRRRRWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWRRRWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
RRRRRRRRRRRRRRRRRWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWRRRRRRRRRRRRRRRRR
"""

defmodule Color do
  def write("R"), do: do_write(" ", "#c9120a")
  def write("B"), do: do_write(" ", "#10116d")
  def write("W"), do: do_write(" ", "#FFFFFF")
  def write("*"), do: do_write("*", "#10116d")
  def write("\n"), do: do_write("\n")
  def write(_), do: nil

  defp do_write(output, color) do
    output |> Palette.bg(color) |> IO.write
  end

  def do_write(output) do
    output |> IO.write
  end
end

defmodule Flag do
  def print(flag) do
    flag |> String.split("") |> Enum.each(&Color.write/1)
  end
end

Flag.print(union_jack)
Flag.print(old_glory)
Flag.print(the_maple_leaf)